name: Deploy Supabase Edge Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install Supabase CLI
        run: |
          curl -sL https://github.com/supabase/cli/releases/latest/download/supabase-cli-linux-amd64 > supabase
          chmod +x supabase
          sudo mv supabase /usr/local/bin/

      - name: Deploy Supabase Edge Function
        run: |
          supabase functions deploy fetchMedia --project-ref ${{ secrets.SUPABASE_PROJECT_ID }} --no-verify-jwt
        working-directory: ./functions
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
